source admin.sql;
source doctor.sql;
source doctor_availability.sql;
source doctor_user_message.sql;
source patient.sql;
source patient_allergy.sql;
source payment_information.sql;
source prescription.sql;
source rating.sql;
source surgery.sql;
source surgery_preoperative_medication.sql
source user.sql;
source visit.sql;
source visit_diagnosis.sql;