SHOW TABLES;
SHOW COLUMNS FROM admin;
SHoW COLUMNS FROM appointment_request;
SHOW COLUMNS FROM doctor;
SHOW COLUMNS FROM doctor_availability;
SHOW COLUMNS FROM doctor_user_message;
SHOW COLUMNS FROM patient;
SHOW COLUMNS FROM patient_allergy;
SHOW COLUMNS FROM payment_information;
SHOW COLUMNS FROM prescription;
SHOW COLUMNS FROM rating;
SHOW COLUMNS FROM surgery;
SHOW COLUMNS FROM surgery_preoperative_medication;
SHOW COLUMNS FROM user;
SHOW COLUMNS FROM visit;
SHOW COLUMNS FROM visit_diagnosis;
